In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model, preprocessing

In [2]:
phi = np.loadtxt('train.csv', dtype='float', delimiter=',', skiprows=1, usecols=(1, 13))
phi

array([[9.55770e-01, 1.72800e+01],
       [2.87500e-02, 6.21000e+00],
       [1.22358e+00, 4.59000e+00],
       [5.66637e+00, 1.65900e+01],
       [4.54400e-02, 9.09000e+00],
       [1.06590e-01, 5.57000e+00],
       [5.11358e+01, 1.01100e+01],
       [3.32105e+00, 2.68200e+01],
       [1.05393e+00, 6.58000e+00],
       [2.45220e-01, 1.59400e+01],
       [5.78340e-01, 7.44000e+00],
       [3.53700e-02, 9.50000e+00],
       [3.84970e+00, 1.32700e+01],
       [3.83518e+01, 3.05900e+01],
       [3.58090e-01, 9.71000e+00],
       [1.58603e+01, 2.43900e+01],
       [6.44405e+00, 1.20300e+01],
       [5.82115e+00, 1.02900e+01],
       [3.50200e-02, 3.33000e+00],
       [1.20482e+01, 1.41000e+01],
       [6.66400e-02, 5.33000e+00],
       [5.37000e-01, 1.16500e+01],
       [5.57780e-01, 1.69600e+01],
       [7.90410e-01, 5.98000e+00],
       [3.30450e-01, 1.08800e+01],
       [6.58800e-02, 7.56000e+00],
       [7.72990e-01, 1.28000e+01],
       [5.37200e-02, 7.39000e+00],
       [8.26500e-02,

In [3]:
y = np.loadtxt('train.csv', dtype='float', delimiter=',', skiprows=1,
               usecols= 13, ndmin=2)
y

array([[17.28],
       [ 6.21],
       [ 4.59],
       [16.59],
       [ 9.09],
       [ 5.57],
       [10.11],
       [26.82],
       [ 6.58],
       [15.94],
       [ 7.44],
       [ 9.5 ],
       [13.27],
       [30.59],
       [ 9.71],
       [24.39],
       [12.03],
       [10.29],
       [ 3.33],
       [14.1 ],
       [ 5.33],
       [11.65],
       [16.96],
       [ 5.98],
       [10.88],
       [ 7.56],
       [12.8 ],
       [ 7.39],
       [ 8.58],
       [ 9.52],
       [10.58],
       [12.6 ],
       [11.41],
       [13.15],
       [14.98],
       [28.28],
       [ 9.38],
       [ 4.74],
       [ 8.79],
       [13.34],
       [ 4.69],
       [16.03],
       [ 9.59],
       [18.8 ],
       [ 8.93],
       [13.83],
       [ 7.53],
       [16.94],
       [17.6 ],
       [15.7 ],
       [34.02],
       [16.14],
       [12.12],
       [ 5.98],
       [11.45],
       [30.81],
       [10.97],
       [ 9.67],
       [ 4.38],
       [10.3 ],
       [ 8.77],
       [31.99],
       [

In [4]:
phi_test = np.loadtxt('test.csv', dtype='float', delimiter=',', skiprows=1, usecols=(1, 13))
phi_test

array([[1.06120e-01, 1.24000e+01],
       [3.41090e-01, 6.12000e+00],
       [1.22472e+01, 1.56900e+01],
       [2.24890e-01, 2.04500e+01],
       [1.80028e+00, 1.21400e+01],
       [5.18800e-02, 1.28600e+01],
       [3.25430e-01, 1.53900e+01],
       [2.99160e-01, 1.30000e+01],
       [3.35900e-02, 1.98000e+00],
       [1.19511e+01, 1.21300e+01],
       [7.02200e-02, 1.01100e+01],
       [1.41385e+00, 1.51200e+01],
       [2.79570e-01, 1.35900e+01],
       [9.59571e+00, 2.03100e+01],
       [1.65660e+00, 1.41000e+01],
       [4.59000e-02, 7.60000e+00],
       [1.71200e-01, 1.86600e+01],
       [1.91860e-01, 5.08000e+00],
       [6.29760e-01, 8.26000e+00],
       [4.54192e+00, 7.79000e+00],
       [2.30040e+00, 1.11000e+01],
       [2.01019e+00, 3.70000e+00],
       [4.81900e-02, 6.57000e+00],
       [1.15779e+01, 2.56800e+01],
       [2.89600e-01, 2.11400e+01],
       [1.35222e+01, 1.33300e+01],
       [7.75223e+00, 1.62300e+01],
       [1.73310e-01, 1.20100e+01],
       [9.51200e-02,

In [5]:
phi = np.concatenate((phi, np.ones((400, 1))), axis=1)
phi

array([[ 0.95577, 17.28   ,  1.     ],
       [ 0.02875,  6.21   ,  1.     ],
       [ 1.22358,  4.59   ,  1.     ],
       ...,
       [ 6.65492, 13.99   ,  1.     ],
       [ 0.13117, 14.09   ,  1.     ],
       [ 0.06466,  4.97   ,  1.     ]])

In [6]:
phi_test = np.concatenate((phi_test, np.ones((105,1))), axis=1)
phi_test

array([[1.06120e-01, 1.24000e+01, 1.00000e+00],
       [3.41090e-01, 6.12000e+00, 1.00000e+00],
       [1.22472e+01, 1.56900e+01, 1.00000e+00],
       [2.24890e-01, 2.04500e+01, 1.00000e+00],
       [1.80028e+00, 1.21400e+01, 1.00000e+00],
       [5.18800e-02, 1.28600e+01, 1.00000e+00],
       [3.25430e-01, 1.53900e+01, 1.00000e+00],
       [2.99160e-01, 1.30000e+01, 1.00000e+00],
       [3.35900e-02, 1.98000e+00, 1.00000e+00],
       [1.19511e+01, 1.21300e+01, 1.00000e+00],
       [7.02200e-02, 1.01100e+01, 1.00000e+00],
       [1.41385e+00, 1.51200e+01, 1.00000e+00],
       [2.79570e-01, 1.35900e+01, 1.00000e+00],
       [9.59571e+00, 2.03100e+01, 1.00000e+00],
       [1.65660e+00, 1.41000e+01, 1.00000e+00],
       [4.59000e-02, 7.60000e+00, 1.00000e+00],
       [1.71200e-01, 1.86600e+01, 1.00000e+00],
       [1.91860e-01, 5.08000e+00, 1.00000e+00],
       [6.29760e-01, 8.26000e+00, 1.00000e+00],
       [4.54192e+00, 7.79000e+00, 1.00000e+00],
       [2.30040e+00, 1.11000e+01, 1.0000

In [7]:
for i in range(0, 13):
    col_max = max(phi[:, i])
    col_min = min(phi[:, i])
    phi[:, i] = (phi[:, i] - col_min) / (col_max - col_min)
    phi_test[:, i] = (phi_test[:, i] - col_min) / (col_max - col_min)
   


    

C:\Users\Snega\AppData\Local\Temp\ipykernel_16988\515506104.py:4: RuntimeWarning: invalid value encountered in true_divide
  phi[:, i] = (phi[:, i] - col_min) / (col_max - col_min)
C:\Users\Snega\AppData\Local\Temp\ipykernel_16988\515506104.py:5: RuntimeWarning: invalid value encountered in true_divide
  phi_test[:, i] = (phi_test[:, i] - col_min) / (col_max - col_min)


IndexError: index 3 is out of bounds for axis 1 with size 3

In [8]:
y = np.log(y)
y

array([[2.84954976],
       [1.8261609 ],
       [1.52388002],
       [2.8088001 ],
       [2.20717491],
       [1.71739505],
       [2.31352503],
       [3.28914788],
       [1.88403475],
       [2.76883167],
       [2.00687085],
       [2.2512918 ],
       [2.58550585],
       [3.42067316],
       [2.27315628],
       [3.19417321],
       [2.48740353],
       [2.33117255],
       [1.2029723 ],
       [2.6461748 ],
       [1.67335124],
       [2.45530618],
       [2.83085763],
       [1.78842057],
       [2.38692624],
       [2.02287119],
       [2.54944517],
       [2.00012773],
       [2.14943391],
       [2.25339485],
       [2.35896543],
       [2.53369681],
       [2.43449016],
       [2.57642176],
       [2.70671598],
       [3.34215484],
       [2.23857976],
       [1.55603714],
       [2.17361471],
       [2.59076704],
       [1.54543258],
       [2.77446197],
       [2.26072089],
       [2.93385687],
       [2.18941639],
       [2.62684015],
       [2.01889504],
       [2.829

In [9]:
def delta_w(p, phi, w):
    if p == 2:
        deltaw = (2 * (np.dot(np.dot(np.transpose(phi), phi), w) -
                       np.dot(np.transpose(phi), y)) +
                  lambd * p * np.power(np.absolute(w), (p - 1)))
    if p < 2 and p > 1:
        deltaw = (2 * (np.dot(np.dot(np.transpose(phi), phi), w) -
                       np.dot(np.transpose(phi), y)) +
                  lambd * p * np.power(np.absolute(w), (p - 1)) * np.sign(w))
    return deltaw


In [10]:
filenames = {'output.csv': 2.0,
             'output_p1.csv': 1.75,
             'output_p2.csv': 1.5,
             'output_p3.csv': 1.3
             }

In [11]:
for (fname, p) in filenames.items():
    # Set initial w to zeros
    w = np.zeros((14, 1))

    # Hyperparameter lambda value
    lambd = 0.2

    # Maximum step size
    t = 0.00012

    # Calculate new value of w
    w_new = w - t * delta_w(p, phi, w)

    i = 0
    # Repeat steps until error between consecutive w is less than threshold
    while(np.linalg.norm(w_new-w) > 10 ** -10):
        w = w_new
        w_new = w - t * delta_w(p, phi, w)
        i = i + 1

    # Load values of id
    id_test = np.loadtxt('test.csv', dtype='int', delimiter=',',
                         skiprows=1, usecols=0, ndmin=2)

    # Calculate y for test data
    y_test = np.exp(np.dot(phi_test, w_new))

    # Save the ids and y
    np.savetxt(fname, np.concatenate((id_test, y_test), axis=1),
               delimiter=',', fmt=['%d', '%f'], header='ID,MEDV', comments='')

ValueError: shapes (3,3) and (14,1) not aligned: 3 (dim 1) != 14 (dim 0)